### PR TITLE
Binary releases (try #2)

### PR DESCRIPTION
**Pull request by guregu**
Same as #118, I think it got overwritten in the history somehow

### CODE REVIEW

**Comment by guregu** [comment]
OK cool. Try pushing a new tag and let's see if it works 🙏

**Comment by guregu** [comment]
Hmm, seems like the jobs are choking 😱 
I'll make a patch real quick 🙇

**Comment by infradig** [comment]
Build: Some jobs were not successful

View workflow run
<https://github.com/trealla-prolog/trealla/actions/runs/4191126921>

[image: WebAssembly]

Build / WebAssembly
Failed in 5 seconds
[image: annotations for Build / WebAssembly] 2
<https://github.com/trealla-prolog/trealla/actions/runs/4191126921>
[image: Native (ubuntu-latest)]

Build / Native (ubuntu-latest)
Succeeded in 46 seconds
[image: Native (macos-latest)]

Build / Native (macos-latest)
Succeeded in 4 minutes and 28 seconds

**Comment by infradig** [comment]
2s
Run ***@***.***
2s
Set environment (1/3)
0s
1
<https://github.com/trealla-prolog/trealla/actions/runs/4191126921/jobs/7265236062#step:3:1>Run
echo "WASI_VERSION_FULL=${WASI_VERSION}.0" >> $GITHUB_ENV
9
<https://github.com/trealla-prolog/trealla/actions/runs/4191126921/jobs/7265236062#step:3:10>Error:
Unable to process file command 'env' successfully.
10
<https://github.com/trealla-prolog/trealla/actions/runs/4191126921/jobs/7265236062#step:3:11>Error:
Invalid format '2.9.5'
Set environment (2/3)
0s
Set environment (3/3)
0s
Add Homebrew to $PATH
0s
Install WASI SDK
0s
Install Binaryen
0s
Setup Wasmer
0s
Build
0s
Test
0s
Upload artifacts
0s
Publish on WAPM
0s
Complete job
0s

**Comment by guregu** [comment]
Hmm, it seems that release was targeted at an old version (188cd64def556bde17fb09d55740962585eee02a)
Can you try to cut a tag from a8a22e6c73c700520e085cff4ec99098afe3f8f7?

**Comment by infradig** [comment]
No idea what that means.

**Comment by guregu** [comment]
Ah, sorry about that. Basically, that build was using the old script (before this PR). I think it breaks when two tags point to the same commit. The breaking part was removed in this PR.
If you create a new tag from the current main branch it might work.

**Comment by guregu** [comment]
I think you need to `git pull` before you make the tag.

**Comment by infradig** [comment]
Is it trigger both on a push to main & a tag?

**Comment by guregu** [comment]
OK I think I can see what happened before, why the commit got removed from the history.
Are you force-pushing your local branch?
This PR got removed from the history again.

It's set up to release from tags only, but it should run on commits to main and PRs.

**Comment by infradig** [comment]
Yeah a -f. No real reason, My up-array just grabs it!

**Comment by guregu** [comment]
Hahaha alright. Let's try again. Third time's the charm :)
Sorry about this

**Pull request merged**
