### PR TITLE
Binary releases (try #3)

### PR DESCRIPTION
**Pull request by guregu**
OK, here's the plan:
- Merge this
- Make sure you `git pull` and the latest commit is from this PR (this is where we've been having trouble)
- Then create a new tag & push

### CODE REVIEW

**Comment by guregu** [comment]
We can see that the build is successful in this PR, so I think as long as you can get it merged into your local dev environment it should be good.

**Comment by infradig** [comment]
The pipeline seems to be flowing again. This is just like at work.

**Comment by guregu** [comment]
Yay! It worked! https://github.com/trealla-prolog/trealla/releases/tag/v2.10.5
Thanks a bunch 🎉 

Please feel free to make an issue and assign it to me if anything breaks. I'll take care of the boring work stuff

**Comment by infradig** [comment]
No, thank you.

**Pull request merged**
